name: evaluate-pr

on:
  push:
    branches:
      - first-pr

jobs:
  download-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Required, workflow file name or ID
          workflow: generate-baseline
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          workflow_conclusion: success
          # Optional, will use the branch
          branch: main
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          # name: phpstan-baseline.neon
          # Optional, directory where to extract artifact(s), defaults to current directory
          # path: phpstan-baseline.neon
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Analyze code
        uses: php-actions/phpstan@v3
        with:
          path: src/
          configuration: phpstan-use-baseline.neon
