name: evaluate-pr

on:
  push:
    branches:
      - first-pr
  pull_request: {}

jobs:
  download-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: 24222701
          workflow_conclusion: success
          commit: a7fa7ee99b3c7703f100080703207d4de1274cad
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Analyze code
        uses: php-actions/phpstan@v3
        with:
          path: src/
          configuration: phpstan-use-baseline.neon
