name: evaluate-pr

on:
  push:
    branches:
      - first-pr
  #pull_request: {}

jobs:
  download-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: .github/workflows/generate-baseline.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: phpstan-baseline.neon
      - name: phpstan
        run: |
          php vendor/bin/phpstan analyse src/ --level=7 --error-format=github --configuration=phpstan-use-baseline.neon
